Poodle/Poodle/Controllers/SubscriptionController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Poodle.Services.Constants;
using Poodle.Services.Contracts;
using Poodle.Services.Dtos;
using Poodle.Services.Exceptions;
using Poodle.Web.Helpers;

namespace Poodle.Web.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly ISubscriptionService subscriptionService;

        public SubscriptionController(ISubscriptionService subscriptionService)
        {
            this.subscriptionService = subscriptionService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        [HttpPost]        
        public async Task<IActionResult> SignUp(string email)
        {
            if (email == null)
            {
                this.RedirectToAction("Index", "Home");
            }

            try
            {
                await this.subscriptionService.Add(email);
                this.ViewData["SuccessMessage"] = ConstantsContainer.SUBSCRIPTION_SUCCESS;
                return this.View(viewName: "Success");
            }
            catch (DuplicateEntityException e)
            {
                this.ViewData["ErrorMessage"] = e.Message;
                return this.View(viewName: "Error");
            }
           
        }
        
        public async Task<IActionResult> Delete()
        {
            try
            {
                string email = this.HttpContext.Session.GetString("CurrentUserEmail");
                await this.subscriptionService.Delete(email);
                this.ViewData["SuccessMessage"] = ConstantsContainer.SUBSCRIPTION_REMOVED;
                return this.View(viewName: "Success");
            }
            catch (EntityNotFoundException e)
            {
                this.ViewData["ErrorMessage"] = e.Message;
                return this.View(viewName: "Error");
            }
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Send(NewsLetterModel newsletter)
        {
            var subscribers = await this.subscriptionService.GetAll();

            foreach (var item in subscribers)
            {
                MailHelper.Send("Zahari.V.Yordanov@gmail.com", item.EmailAddress, newsletter.Subject, newsletter.Body);
            }
            
            this.ViewData["SuccessMessage"] = "Newsletter sent to every one";
            return this.View(viewName: "Success");
        }
    }
}

Poodle/Poodle/Views/Subscription/Index.cshtml
@{
    ViewData["Title"] = "NewsLetter";
}
@model NewsLetterModel
<!-- Registration Start -->
<div class="container-fluid bg-registration py-5" style="margin: 90px 0;">
    <div class="container py-5">
        <div class="row align-items-center">            
            <div class="col-lg-5">
                <div class="card border-0">
                    <div class="card-header bg-light text-center p-4">
                        <h1 class="m-0">Create NewsLetter</h1>                        
                    </div>
                    <div class="card-body rounded-bottom bg-primary p-5">
                        <form asp-controller="Subscription" asp-action="Send" method="post">
                            @*@Html.AntiForgeryToken()*@
                            <div class="form-group">
                                <input type="text" name="subject" asp-for="@Model.Subject" class="form-control border-0 p-4" placeholder="Subject" required="required" />
                                <span class="text-danger" asp-validation-for="@Model.Subject"></span>
                            </div>
                            <div class="form-group">
                                <textarea cols="20" rows="5" name="body" asp-for="@Model.Body" class="form-control border-0 p-4" placeholder="Your nesletter content" required="required"></textarea>
                                <span class="text-danger" asp-validation-for="@Model.Body"></span>
                            </div>
                            <div>
                                <button class="btn btn-dark btn-block border-0 py-3" type="submit">Send Mail</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Registration End -->